name: docker tests
on: [push,pull_request]
jobs:
  checkbins:
    runs-on: ubuntu-20.04
    container: registry.gitlab.com/k9ert/specter-desktop/cypress-python:20201111231032
    steps:
      - name: Checkout
      - run: |
          ls -s
          docker version